#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Wed Feb 21 15:22:14 2007

import wx
import os
import globals
import webbrowser
import platform
if wx.Platform == '__WXMSW__':
    from wx.lib.flashwin import FlashWindow

class PanelHelp(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelHelp.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.label_info1 = wx.StaticText(self, -1, _("We need your help to keep up Subdownloader, you can help us in many ways:"))
        self.label_info2 = wx.StaticText(self, -1, _("- Uploading a lot of subtitles to grow up the database quickly"))
        self.label_info4 = wx.StaticText(self, -1, _("- Contact us to translate the program in your language"))
        self.label_info5 = wx.StaticText(self, -1, _("- DONATE US so we could buy some kebap or chinese food sometimes :-)"))
        self.button_donate = wx.BitmapButton(self, -1, wx.NullBitmap)
        self.label_info6 = wx.StaticText(self, -1, _("- Send us some FEEDBACK"))
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.button_sendfeedback = wx.Button(self, -1, _("Send Feedback"))
        self.label_chat = wx.StaticText(self, -1, _("    - Chat with us:"))
        self.flash_widget = wx.StaticText(self, -1, _("   capiscuas@gmail.com"))
        self.static_line_2 = wx.StaticLine(self, -1)
        self.static_line_2_copy = wx.StaticLine(self, -1)
        self.static_line_3 = wx.StaticLine(self, -1)
        self.static_line_1 = wx.StaticLine(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        self.button_donate.Destroy()
        self.button_donate = wx.BitmapButton(self, -1, wx.Bitmap(os.path.join(globals.sourcefolder,"donate.gif"), wx.BITMAP_TYPE_ANY))
        self.button_sendfeedback.Disable()
        self.Bind(wx.EVT_TEXT,self.OnTypeText,self.text_ctrl_1)
        
      
        if wx.Platform == '__WXMSW__':
            try:
                flash = FlashWindow(self, style=wx.SUNKEN_BORDER)
                self.flash_widget.Destroy()
                self.flash_widget = flash
                self.flash_widget.movie = "http://www.plugoo.com/plug.swf?go=R2KUWFGPB2L"      
            except:
                pass
        
        # begin wxGlade: PanelHelp.__set_properties
        self.label_info1.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_info1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_info2.SetForegroundColour(wx.Colour(255, 0, 0))
        self.label_info2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_info4.SetForegroundColour(wx.Colour(143, 143, 188))
        self.label_info4.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_info5.SetForegroundColour(wx.Colour(35, 35, 142))
        self.label_info5.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_donate.SetSize(self.button_donate.GetBestSize())
        self.label_info6.SetMinSize((166, 16))
        self.label_info6.SetForegroundColour(wx.Colour(255, 127, 0))
        self.label_info6.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_1.SetMinSize((200, 34))
        self.label_chat.SetForegroundColour(wx.Colour(255, 0, 127))
        self.label_chat.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.flash_widget.SetMinSize((220, 330))
        self.flash_widget.SetForegroundColour(wx.Colour(176, 0, 255))
        self.flash_widget.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PanelHelp.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.label_info1, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_2.Add(self.label_info2, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_2.Add(self.label_info4, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_2.Add(self.label_info5, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_2.Add(self.button_donate, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 9)
        sizer_4.Add(self.label_info6, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_4.Add(self.text_ctrl_1, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_3.Add((20, 0), 0, wx.EXPAND, 0)
        sizer_3.Add(self.button_sendfeedback, 0, wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_3, 0, wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_chat, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_5.Add(self.flash_widget, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        sizer_1.Add(sizer_5, 0, 0, 0)
        sizer_2.Add(sizer_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_2_copy, 0, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_1, 0, wx.EXPAND, 30)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        sizer_2.SetSizeHints(self)
        # end wxGlade
        
        
        self.Bind(wx.EVT_BUTTON, self.OnDonate, self.button_donate)
        self.Bind(wx.EVT_BUTTON, self.OnSendFeedBack, self.button_sendfeedback)

    def OnTypeText(self,evt):
        if len(self.text_ctrl_1.GetValue()):
            self.button_sendfeedback.Enable()
        else:
            self.button_sendfeedback.Disable()
    

    def OnSendFeedBack(self,evt):
        globals.xmlrpc_server.SendBug("FEEDBACK\nVersion: " + globals.version + "\n" +platform.platform() + "\n\nMessage:\n" + self.text_ctrl_1.GetValue(),globals.logged_as,"IP")
        wx.MessageBox(_("Thank you very much"))
        
    def OnDonate(self,evt):
        try:
            webbrowser.open("http://sourceforge.net/donate/index.php?group_id=171818")
        except:
            msg = _("Error opening link")
            wx.MessageBox(msg + " http://sourceforge.net/donate/index.php?group_id=171818")
# end of class PanelHelp


