#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Mon Jul 17 01:51:38 2006

import wx
import os
import  wx.html as  html
import webbrowser
import globals


class MyHtmlWindow(html.HtmlWindow):
 def __init__(self, parent, id):
        html.HtmlWindow.__init__(self, parent, id, style=wx.NO_FULL_REPAINT_ON_RESIZE)
        if "gtk2" in wx.PlatformInfo:
            self.SetStandardFonts()
            
 def OnLinkClicked(self, linkinfo):
	lnk = linkinfo.GetHref()
	
	try:
	    webbrowser.open(lnk)
	except:
	    msg = _("Error opening link")
            wx.MessageBox(msg+ lnk)
            
class SubWindow(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SubWindow.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.ani = wx.StaticBitmap(self.panel_1, -1, wx.NullBitmap)
        self.label_function = wx.StaticText(self.panel_1, -1, _("No Subtitle found."))
        self.label_text1 = wx.StaticText(self.panel_1, -1, _("Please be the first to upload the subtitles\nso other people can find them soon."))
        self.label_text2 = wx.StaticText(self.panel_1, -1, _("Where can I download subtitles?"))
        self.html_window = MyHtmlWindow(self.panel_1, -1)
        self.button_cancel = wx.Button(self.panel_1, -1, _("Close"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        self.ani.Destroy()
        self.ani = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap(os.path.join(globals.sourcefolder,"images/buttons/cancel.png"), wx.BITMAP_TYPE_ANY))
        
        self.is_canceled = False
        self.button_cancel.SetLabel("Close")
        self.Bind(wx.EVT_BUTTON, self.OnCancelButton, self.button_cancel)
        
        page = os.path.join(globals.sourcefolder, 'data/html/search_links.htm')
        self.html_window.LoadPage(page)

        def OnOpeningURL( self, type, url ):
            if url.find('cid:')==0:
                nu = self.msg.uri().asString() + '#' + url
                return nu
            elif url.find( self.msg.uri().asString() + '#' )==0:
                return wx.html.HTML_OPEN
            if type==wx.html.HTML_URL_PAGE:
                return wx.html.HTML_OPEN
            return wx.html.HTML_BLOCK
    
        # begin wxGlade: SubWindow.__set_properties
        self.SetTitle(_("No subtitles found. Please upload it."))
        self.label_function.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_text1.SetForegroundColour(wx.Colour(95, 159, 159))
        self.label_text1.SetFont(wx.Font(12, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_text2.SetForegroundColour(wx.Colour(255, 0, 0))
        self.label_text2.SetFont(wx.Font(14, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.html_window.SetMinSize((500, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SubWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.ani, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.label_function, 0, wx.LEFT|wx.RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_text1, 0, wx.LEFT|wx.RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add(self.label_text2, 0, wx.LEFT|wx.RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add(self.html_window, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_cancel, 0, wx.TOP|wx.ALIGN_CENTER_HORIZONTAL, 20)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(sizer_2)
        sizer_2.Fit(self.panel_1)
        sizer_2.SetSizeHints(self.panel_1)
        sizer_1.Add(self.panel_1, 1, 0, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade
    def OnCancelButton(self,evt):
        self.is_canceled = True
        self.Destroy()
        
    def OnLinkopensubtitles(self,evt):
        try:
            webbrowser.open(globals.MakeOSLink(""))
        except:
            msg = _("Error opening link")
            wx.MessageBox(msg + " " + globals.MakeOSLink(""))
    def EndBusyCursor(self):
        wx.EndBusyCursor()
    def BeginBusyCursor(self):
        wx.BeginBusyCursor()
# end of class SubWindow


