.TH SUBDOWNLOADER 1 "2008-06-02"
.\" --------------------------------------------------------
.SH NAME
subdownloader \- computer dictionary with several dictionary format support
.\" --------------------------------------------------------
.SH SYNOPSIS
.B opendict
.sp
or select
.B Dictionary OpenDict
from the
.B Utility
submenu of the Applications menu if using Gnome Desktop Environment.
.\" --------------------------------------------------------
.SH DESCRIPTION
.B OpenDict
is a free cross-platform dictionary program. 
It works with DICT, Slowo and Mova dictionaries. It also supports plug-in
dictionaries that may be created for almost any data source. OpenDict is a
client for DICT servers.

.\" --------------------------------------------------------
.SH SEE ALSO
.BR http://opendict.idiles.com
.\" --------------------------------------------------------
.SH AUTHORS
.B
opendict
was written by Martynas Jocius <martynas.jocius@idiles.com>.

.ad l
This manual page was written by Kestutis Biliunas
.nh 
<kebil@kaunas.init.lt>,
.hy
for the Debian system (but may be used by others).
