.TH SUBDOWNLOADER 1 "2008-06-02"
.\" --------------------------------------------------------
.SH NAME
subdownloader - the subtitle downloader
.\" --------------------------------------------------------
.SH SYNOPSIS
.B subdownloader
[\-h] [\--help] [\-g] [\--gui] [\-c] [\--cli] [\-d] [\--debug] [\-q] [\--quiet] [\-T] [\--test] [\-H] [\--human] [\-n] [\--nerd] [\-D] [\--download] [\-U] [\--upload] [\-L] [\--list] [\-V <
.I path
>] [\--video=<
.I path
>] [\-l <
.I language
>] [\--lang=<
.I language
>] [\-i] [\--interactive] [\--sol] [\--los] [\-u <
.I username
>] [\--user=<
.I username
>] [\-p <
.I password
>] [\--passwd=<
.I password
>] [\-s <
.I address
>] [\--server=<
.I address
>] [\-P <
.I address
>] [\--proxy=<
.I address
>] [\--version]
.\" --------------------------------------------------------
.SH DESCRIPTION
.B SubDownloader
is a Free Open Source tool written in Python for automatic download/upload subtitles for videofiles (DIVX,MPEG,AVI,etc) and DVD's using fast hashing.
.\" --------------------------------------------------------
.SH OPTIONS
.B "-h --help"
.RS
Show SubDownloader command-line options.
.RE

.B "-g, --gui"
.RS
Run application in GUI mode. This is the default.
.RE

.B "-c, --cli"
.RS
Run application in CLI mode.
.RE

.B "-d, --debug"
.RS
Print debug messages to stout and logfile.
.RE

.B "-q, --quiet"
.RS
Don't print status messages to stdout.
.RE

.B "-T, --test"
.RS
Used by developers for testing.
.RE

.B "-H, --human"
.RS
Print human readable messages. Default for CLI mode.
.RE

.B "-n, --nerd"
.RS
Print messages with more details.
.RE

.B "-D, --download"
.RS
Download a subtitle. Default for CLI mode.
.RE

.B "-U, --upload"
.RS
Upload a subtitle.
.RE

.B "-L, --list"
.RS
List available subtitles without downloading.
.RE

.B -V
.I path
,
.B --video=
.I path
.RS
Full path to your video(s). Don't use '~'.
.RE

.B -l
.I language
,
.B --lang=
.I language
.RS
Used in subtitle download and upload preferences.
.RE

.B "-i, --interactive"
.RS
Prompt user when decisions need to be done.
.RE

.B "--rename-subs"
.RS
Rename subtitles to match movie file name
.RE

.B "--keep-names"
.RS
Keep original subtitle names
.RE

.B "--sol"
.RS
\'Server Over Local\' overwrites local subtitle with one from server. This is in cases when local subtitle isn't found on server, but server has subtitles for the movie.
.RE

.B "--los"
.RS
\'Local Over Server\' keeps local subtitles, even if another is found on server. This is the default.
.RE

.B -u
.I username
,
.B --user=
.I username
.RS
Opensubtitles.com username. Must be set in upload mode. Default is blank (anonymous).
.RE

.B -p
.I password
,
.B --passwd=
.I password
.RS
Opensubtitles.com password. Must be set in upload mode. Default is blank (anonymous).
.RE

.B -s
.I address
,
.B --server=
.I address
.RS
Server address of Opensubtitles API.
.RE

.B -P
.I address
,
.B --proxy=
.I proxy
.RS
Proxy to use on internet connections.
.RE

.B --version
.RS
Show program's version number and exit.
.RE
.\" --------------------------------------------------------
.SH SEE ALSO
.BR http://www.subdownloader.net
.\" --------------------------------------------------------
.SH AUTHORS
Ivan Garcia
.BR <ivangarcia@subdownloader.net>

Marco Ferreira
.BR <mferreira@subdownloader.net>

Marco Rodrigues
.BR <gothicx@gmail.com>
