#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Fri Oct 20 11:15:01 2006

import wx
import globals
import platform
import webbrowser

class MyDialog(wx.Dialog):
    def __init__(self,update_list, *args, **kwds):
        self.update_list = update_list
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_info = wx.StaticText(self.panel_1, -1, _("A new version of SubDownloader has been released."))
        self.label_1 = wx.StaticText(self.panel_1, -1, _("NEW VERSION: "))
        self.label_newversion = wx.StaticText(self.panel_1, -1, _("UNKNOWN"))
        self.label_2 = wx.StaticText(self.panel_1, -1, _("CURRENT VERSION:"))
        self.label_currentversion = wx.StaticText(self.panel_1, -1, _("UNKNOWN"))
        self.label_changes = wx.StaticText(self.panel_1, -1, _("Changes in the new version:"))
        self.text_changes = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.button_download = wx.Button(self.panel_1, -1, _("Update"))
        self.static_line_1 = wx.StaticLine(self.panel_1, -1)
        self.button_close = wx.Button(self.panel_1, -1, _("Close"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle(_("New Update"))
        self.label_newversion.SetForegroundColour(wx.Colour(255, 0, 0))
        self.label_newversion.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_currentversion.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_changes.SetMinSize((254,100))
        self.button_download.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        sizer_2.Add(self.label_info, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 4)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.label_newversion, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_currentversion, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.label_changes, 0, wx.TOP|wx.ADJUST_MINSIZE, 6)
        sizer_2.Add(self.text_changes, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.button_download, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.static_line_1, 0, wx.BOTTOM|wx.EXPAND, 30)
        sizer_3.Add((20, 0), 0, wx.EXPAND, 0)
        sizer_3.Add(self.button_close, 0, wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(sizer_3, 0, wx.ALIGN_RIGHT, 0)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(sizer_2)
        sizer_2.Fit(self.panel_1)
        sizer_2.SetSizeHints(self.panel_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade
        
        self.Bind(wx.EVT_BUTTON, self.OnClose, self.button_close)
        self.Bind(wx.EVT_BUTTON, self.OnUpdate, self.button_download)
        self.label_newversion.SetLabel(self.update_list["version"])
        self.label_currentversion.SetLabel(globals.version)
        self.text_changes.SetValue(self.update_list["comments"].replace("|","\n"))
        
    def OnClose(self,evt):
        self.Destroy()
    def OnUpdate(self,evt):
        
        if platform.system() == "Windows":
           try:
               webbrowser.open(self.update_list["url_windows"])
           except: 
               msg = _("Error opening link")
               wx.MessageBox(msg + " "+ self.update_list["url_windows"])
        else:
           try:
               webbrowser.open(self.update_list["url_linux"])
           except: 
               msg = _("Error opening link")
               wx.MessageBox(msg + " "+ self.update_list["url_linux"])
           
        globals.preferences_list["no_show_update_version"] = self.update_list["version"]
        self.Destroy()
        

# end of class MyDialog


