#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Sat Aug 26 21:30:45 2006
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Sun Jul 16 22:57:38 2006
#Copyright (C) IVAN GARCIA capiscuas@gmail.com

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import wx
import webbrowser
import wx.lib.hyperlink as hl
import globals

class UploadConfirmation(wx.Dialog):
    def __init__(self, movietitle,sublanguage,idsubtitle,*args, **kwds):
        self.movietitle = movietitle
        self.sublanguage = sublanguage
        self.idsubtitle = idsubtitle
        # begin wxGlade: UploadConfirmation.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, _("The video hash of "))
        self.link_already = hl.HyperLinkCtrl(self, -1, "this subtitle", URL="")
        self.label_1_copy = wx.StaticText(self, -1, _(" has been updated."))
        self.label_4_copy = wx.StaticText(self, -1, _("Thank you very much for your collaboration  :-)"))
        self.static_line_1 = wx.StaticLine(self, -1)
        self.label_2 = wx.StaticText(self, -1, _("Movie Title:"))
        self.label_movietitle = wx.StaticText(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, _("Subtitle Language:"))
        self.label_language = wx.StaticText(self, -1, "")
        self.static_line_2 = wx.StaticLine(self, -1)
        self.button_ok = wx.Button(self, -1, _("OK"))
        self.button_wrong = wx.Button(self, -1, _("Report wrong info"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        self.label_movietitle.SetLabel(self.movietitle)
        self.label_language.SetLabel(self.sublanguage)
        self.Bind(wx.EVT_BUTTON, self.OnButtonReportWrong, self.button_wrong)
        self.Bind(wx.EVT_BUTTON, self.OnButtonOK, self.button_ok)
        self.link_already.SetBold(True)
        self.link_already.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 1, ""))
        self.link_already.SetUnderlines(link=True, visited=True, rollover=True)
        self.link_already.SetURL(globals.MakeOSLink("subtitles/"+str(self.idsubtitle)))
        self.link_already.Refresh()
        #self.link_already.
        
        # begin wxGlade: UploadConfirmation.__set_properties
        self.SetTitle(_("Subtitle Found..."))
        self.label_1.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.link_already.SetMinSize((100, 23))
        self.link_already.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 1, ""))
        self.label_1_copy.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_4_copy.SetForegroundColour(wx.Colour(127, 0, 255))
        self.label_4_copy.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_movietitle.SetForegroundColour(wx.Colour(47, 47, 79))
        self.label_movietitle.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_language.SetForegroundColour(wx.Colour(66, 111, 66))
        self.label_language.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: UploadConfirmation.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.label_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.link_already, 0, wx.EXPAND, 0)
        sizer_6.Add(self.label_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add(self.label_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_4.Add(self.label_2, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 4)
        sizer_4.Add(self.label_movietitle, 1, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_5.Add(self.label_3, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 4)
        sizer_5.Add(self.label_language, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_2.Add(self.button_ok, 0, wx.RIGHT|wx.TOP|wx.ADJUST_MINSIZE, 4)
        sizer_2.Add(self.button_wrong, 0, wx.RIGHT|wx.TOP|wx.ADJUST_MINSIZE, 4)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade
    def OnButtonReportWrong(self,evt):
        try:
            webbrowser.open(globals.MakeOSLink("report/idsubtitle-" + self.idsubtitle))
        except: 
            wx.MessageBox("Error opening link: "+ globals.MakeOSLink("report/idsubtitle-" + self.idsubtitle))
        self.Destroy()

    def OnButtonOK(self,evt):
        self.Destroy()
        
# end of class UploadConfirmation


