# https://translations.launchpad.net/subdownloader/trunk/+pots/subdownloader
# after download and unzip launchpad-export.tar.gz from po and mo.
mv subdownloader/subdownloader-af.po af/LC_MESSAGES/subdownloader.po
mv subdownloader/subdownloader-en_CA.po en_CA/LC_MESSAGES/subdownloader.po
mv subdownloader/subdownloader-is.po is/LC_MESSAGES/subdownloader.po
mv subdownloader/subdownloader-kn.po kn/LC_MESSAGES/subdownloader.po
mv subdownloader/subdownloader-pt_BR.po pt_BR/LC_MESSAGES/subdownloader.po
mv subdownloader/subdownloader-th.po th/LC_MESSAGES/subdownloader.po
mv subdownloader/subdownloader-zh_CN.po zh_CN/LC_MESSAGES/subdownloader.po
mv subdownloader-ar.po ar/LC_MESSAGES/subdownloader.po
mv subdownloader-ast.po ast/LC_MESSAGES/subdownloader.po
mv subdownloader-bs.po bs/LC_MESSAGES/subdownloader.po
mv subdownloader-ca.po ca/LC_MESSAGES/subdownloader.po
mv subdownloader-en_GB.po en_GB/LC_MESSAGES/subdownloader.po
mv subdownloader-eo.po eo/LC_MESSAGES/subdownloader.po
mv subdownloader-eu.po eu/LC_MESSAGES/subdownloader.po
mv subdownloader-fa.po fa/LC_MESSAGES/subdownloader.po
mv subdownloader-hi.po hi/LC_MESSAGES/subdownloader.po
mv subdownloader-lt.po lt/LC_MESSAGES/subdownloader.po
mv subdownloader-ms.po ms/LC_MESSAGES/subdownloader.po
mv subdownloader-nb.po nb/LC_MESSAGES/subdownloader.po
mv subdownloader-sl.po sl/LC_MESSAGES/subdownloader.po
mv subdownloader-ta.po ta/LC_MESSAGES/subdownloader.po
mv subdownloader-tr.po tr/LC_MESSAGES/subdownloader.po
mv subdownloader-uk.po uk/LC_MESSAGES/subdownloader.po
mv subdownloader-zh_TW.po zh_TW/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-bn.po bn/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-lv.po lv/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-ka.po ka/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-ne.po ne/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-oc.po oc/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-sr\@latin.po sr\@latin/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-nn.po nn/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-zza.po zza/LC_MESSAGES/subdownloader.po
mv locale/subdownloader-zh_HK.po zh_HK/LC_MESSAGES/subdownloader.po
mv po/subdownloader-bg.po bg/LC_MESSAGES/subdownloader.po
mv po/subdownloader-da.po da/LC_MESSAGES/subdownloader.po
mv po/subdownloader-cs.po cs/LC_MESSAGES/subdownloader.po
mv po/subdownloader-de.po de/LC_MESSAGES/subdownloader.po
mv po/subdownloader-el.po el/LC_MESSAGES/subdownloader.po
mv po/subdownloader-es.po es/LC_MESSAGES/subdownloader.po
mv po/subdownloader-et.po et/LC_MESSAGES/subdownloader.po
mv po/subdownloader-fi.po fi/LC_MESSAGES/subdownloader.po
mv po/subdownloader-gl.po gl/LC_MESSAGES/subdownloader.po
mv po/subdownloader-he.po he/LC_MESSAGES/subdownloader.po
mv po/subdownloader-hr.po hr/LC_MESSAGES/subdownloader.po
mv po/subdownloader-hu.po hu/LC_MESSAGES/subdownloader.po
mv po/subdownloader-fr.po fr/LC_MESSAGES/subdownloader.po
mv po/subdownloader-id.po id/LC_MESSAGES/subdownloader.po
mv po/subdownloader-it.po it/LC_MESSAGES/subdownloader.po
mv po/subdownloader-ja.po ja/LC_MESSAGES/subdownloader.po
mv po/subdownloader-ko.po ko/LC_MESSAGES/subdownloader.po
mv po/subdownloader-mk.po mk/LC_MESSAGES/subdownloader.po
mv po/subdownloader-nl.po nl/LC_MESSAGES/subdownloader.po
mv po/subdownloader-pl.po pl/LC_MESSAGES/subdownloader.po
mv po/subdownloader-pt.po pt/LC_MESSAGES/subdownloader.po
mv po/subdownloader-ro.po ro/LC_MESSAGES/subdownloader.po
mv po/subdownloader-ru.po ru/LC_MESSAGES/subdownloader.po
mv po/subdownloader-sk.po sk/LC_MESSAGES/subdownloader.po
mv po/subdownloader-sq.po sq/LC_MESSAGES/subdownloader.po
mv po/subdownloader-sr.po sr/LC_MESSAGES/subdownloader.po
mv po/subdownloader-sv.po sv/LC_MESSAGES/subdownloader.po
mv po/subdownloader-vi.po vi/LC_MESSAGES/subdownloader.po
mv pt pt_PT
mv es es_ES
