# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expiration.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExpirationDialog(object):
    def setupUi(self, ExpirationDialog):
        ExpirationDialog.setObjectName("ExpirationDialog")
        ExpirationDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ExpirationDialog.resize(483, 295)
        ExpirationDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExpirationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_expiration = QtWidgets.QLabel(ExpirationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_expiration.setFont(font)
        self.label_expiration.setObjectName("label_expiration")
        self.verticalLayout.addWidget(self.label_expiration)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonRegister = QtWidgets.QPushButton(ExpirationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonRegister.setFont(font)
        self.buttonRegister.setObjectName("buttonRegister")
        self.horizontalLayout_2.addWidget(self.buttonRegister)
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(ExpirationDialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ExpirationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.activation_email = QtWidgets.QLineEdit(ExpirationDialog)
        self.activation_email.setObjectName("activation_email")
        self.gridLayout.addWidget(self.activation_email, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ExpirationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.activation_fullname = QtWidgets.QLineEdit(ExpirationDialog)
        self.activation_fullname.setObjectName("activation_fullname")
        self.gridLayout.addWidget(self.activation_fullname, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ExpirationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.activation_licensekey = QtWidgets.QLineEdit(ExpirationDialog)
        self.activation_licensekey.setObjectName("activation_licensekey")
        self.gridLayout.addWidget(self.activation_licensekey, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonCancel = QtWidgets.QPushButton(ExpirationDialog)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.buttonActivate = QtWidgets.QPushButton(ExpirationDialog)
        self.buttonActivate.setObjectName("buttonActivate")
        self.horizontalLayout.addWidget(self.buttonActivate)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ExpirationDialog)
        QtCore.QMetaObject.connectSlotsByName(ExpirationDialog)

    def retranslateUi(self, ExpirationDialog):
        _translate = QtCore.QCoreApplication.translate
        ExpirationDialog.setWindowTitle(_translate("ExpirationDialog", "Program has expired"))
        self.label_expiration.setText(_translate("ExpirationDialog", "The program has expired after %d days of usage."))
        self.buttonRegister.setText(_translate("ExpirationDialog", "Register Online..."))
        self.label_5.setText(_translate("ExpirationDialog", "After registering, you will receive a license key via email."))
        self.label.setText(_translate("ExpirationDialog", "Email:"))
        self.label_2.setText(_translate("ExpirationDialog", "Full Name:"))
        self.label_3.setText(_translate("ExpirationDialog", "License key:"))
        self.buttonCancel.setText(_translate("ExpirationDialog", "Cancel"))
        self.buttonActivate.setText(_translate("ExpirationDialog", "Activate"))

