# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName(_fromUtf8("PreferencesDialog"))
        PreferencesDialog.setWindowModality(QtCore.Qt.WindowModal)
        PreferencesDialog.resize(722, 383)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreferencesDialog.sizePolicy().hasHeightForWidth())
        PreferencesDialog.setSizePolicy(sizePolicy)
        PreferencesDialog.setSizeGripEnabled(False)
        PreferencesDialog.setModal(True)
        self.verticalLayout_5 = QtGui.QVBoxLayout(PreferencesDialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(PreferencesDialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_56 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.verticalLayout_4.addWidget(self.label_56)
        self.scrollArea = QtGui.QScrollArea(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 150))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 148))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.optionFilterLangLayout_1 = QtGui.QVBoxLayout()
        self.optionFilterLangLayout_1.setSpacing(5)
        self.optionFilterLangLayout_1.setObjectName(_fromUtf8("optionFilterLangLayout_1"))
        self.horizontalLayout_2.addLayout(self.optionFilterLangLayout_1)
        self.optionFilterLangLayout_2 = QtGui.QVBoxLayout()
        self.optionFilterLangLayout_2.setSpacing(5)
        self.optionFilterLangLayout_2.setObjectName(_fromUtf8("optionFilterLangLayout_2"))
        self.horizontalLayout_2.addLayout(self.optionFilterLangLayout_2)
        self.optionFilterLangLayout_3 = QtGui.QVBoxLayout()
        self.optionFilterLangLayout_3.setSpacing(5)
        self.optionFilterLangLayout_3.setObjectName(_fromUtf8("optionFilterLangLayout_3"))
        self.horizontalLayout_2.addLayout(self.optionFilterLangLayout_3)
        self.optionFilterLangLayout_4 = QtGui.QVBoxLayout()
        self.optionFilterLangLayout_4.setSpacing(5)
        self.optionFilterLangLayout_4.setObjectName(_fromUtf8("optionFilterLangLayout_4"))
        self.horizontalLayout_2.addLayout(self.optionFilterLangLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.optionDownloadFolderAsk = QtGui.QRadioButton(self.groupBox)
        self.optionDownloadFolderAsk.setObjectName(_fromUtf8("optionDownloadFolderAsk"))
        self.verticalLayout_6.addWidget(self.optionDownloadFolderAsk)
        self.optionDownloadFolderSame = QtGui.QRadioButton(self.groupBox)
        self.optionDownloadFolderSame.setChecked(True)
        self.optionDownloadFolderSame.setObjectName(_fromUtf8("optionDownloadFolderSame"))
        self.verticalLayout_6.addWidget(self.optionDownloadFolderSame)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.optionDownloadFolderPredefined = QtGui.QRadioButton(self.groupBox)
        self.optionDownloadFolderPredefined.setObjectName(_fromUtf8("optionDownloadFolderPredefined"))
        self.horizontalLayout_6.addWidget(self.optionDownloadFolderPredefined)
        self.optionPredefinedFolderText = QtGui.QLineEdit(self.groupBox)
        self.optionPredefinedFolderText.setReadOnly(True)
        self.optionPredefinedFolderText.setObjectName(_fromUtf8("optionPredefinedFolderText"))
        self.horizontalLayout_6.addWidget(self.optionPredefinedFolderText)
        self.optionButtonChooseFolder = QtGui.QPushButton(self.groupBox)
        self.optionButtonChooseFolder.setObjectName(_fromUtf8("optionButtonChooseFolder"))
        self.horizontalLayout_6.addWidget(self.optionButtonChooseFolder)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.optionDownloadSameFilename = QtGui.QRadioButton(self.groupBox_2)
        self.optionDownloadSameFilename.setChecked(True)
        self.optionDownloadSameFilename.setObjectName(_fromUtf8("optionDownloadSameFilename"))
        self.verticalLayout_2.addWidget(self.optionDownloadSameFilename)
        self.optionDownloadSameFilenamePlusLang = QtGui.QRadioButton(self.groupBox_2)
        self.optionDownloadSameFilenamePlusLang.setChecked(False)
        self.optionDownloadSameFilenamePlusLang.setObjectName(_fromUtf8("optionDownloadSameFilenamePlusLang"))
        self.verticalLayout_2.addWidget(self.optionDownloadSameFilenamePlusLang)
        self.optionDownloadSameFilenamePlusLangAndUploader = QtGui.QRadioButton(self.groupBox_2)
        self.optionDownloadSameFilenamePlusLangAndUploader.setChecked(False)
        self.optionDownloadSameFilenamePlusLangAndUploader.setObjectName(_fromUtf8("optionDownloadSameFilenamePlusLangAndUploader"))
        self.verticalLayout_2.addWidget(self.optionDownloadSameFilenamePlusLangAndUploader)
        self.optionDownloadOnlineSubName = QtGui.QRadioButton(self.groupBox_2)
        self.optionDownloadOnlineSubName.setObjectName(_fromUtf8("optionDownloadOnlineSubName"))
        self.verticalLayout_2.addWidget(self.optionDownloadOnlineSubName)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.layoutWidget = QtGui.QWidget(self.tab_8)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 521, 52))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_55 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_4.addWidget(self.label_55)
        self.optionDefaultUploadLanguage = QtGui.QComboBox(self.layoutWidget)
        self.optionDefaultUploadLanguage.setMinimumSize(QtCore.QSize(0, 20))
        self.optionDefaultUploadLanguage.setObjectName(_fromUtf8("optionDefaultUploadLanguage"))
        self.horizontalLayout_4.addWidget(self.optionDefaultUploadLanguage)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_52 = QtGui.QLabel(self.tab_9)
        self.label_52.setGeometry(QtCore.QRect(20, 10, 131, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_9)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 241, 67))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_60 = QtGui.QLabel(self.layoutWidget1)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.label_60, 0, 0, 1, 1)
        self.optionProxyHost = QtGui.QLineEdit(self.layoutWidget1)
        self.optionProxyHost.setObjectName(_fromUtf8("optionProxyHost"))
        self.gridLayout.addWidget(self.optionProxyHost, 0, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.layoutWidget1)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout.addWidget(self.label_59, 1, 0, 1, 1)
        self.optionProxyPort = QtGui.QSpinBox(self.layoutWidget1)
        self.optionProxyPort.setMaximum(99999)
        self.optionProxyPort.setProperty("value", 8080)
        self.optionProxyPort.setObjectName(_fromUtf8("optionProxyPort"))
        self.gridLayout.addWidget(self.optionProxyPort, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_61 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.horizontalLayout.addWidget(self.label_61)
        self.optionInterfaceLanguage = QtGui.QComboBox(self.tab_7)
        self.optionInterfaceLanguage.setObjectName(_fromUtf8("optionInterfaceLanguage"))
        self.horizontalLayout.addWidget(self.optionInterfaceLanguage)
        self.helpTranslateButton = QtGui.QPushButton(self.tab_7)
        self.helpTranslateButton.setObjectName(_fromUtf8("helpTranslateButton"))
        self.horizontalLayout.addWidget(self.helpTranslateButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_62 = QtGui.QLabel(self.tab_7)
        self.label_62.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout_5.addWidget(self.label_62)
        self.optionIntegrationExplorer = QtGui.QCheckBox(self.tab_7)
        self.optionIntegrationExplorer.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionIntegrationExplorer.sizePolicy().hasHeightForWidth())
        self.optionIntegrationExplorer.setSizePolicy(sizePolicy)
        self.optionIntegrationExplorer.setMinimumSize(QtCore.QSize(0, 22))
        self.optionIntegrationExplorer.setObjectName(_fromUtf8("optionIntegrationExplorer"))
        self.horizontalLayout_5.addWidget(self.optionIntegrationExplorer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_63 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_4.addWidget(self.label_63, 0, 0, 1, 2)
        self.label_67 = QtGui.QLabel(self.tab_7)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_4.addWidget(self.label_67, 1, 0, 1, 1)
        self.optionVideoAppLocation = QtGui.QLineEdit(self.tab_7)
        self.optionVideoAppLocation.setObjectName(_fromUtf8("optionVideoAppLocation"))
        self.gridLayout_4.addWidget(self.optionVideoAppLocation, 1, 1, 1, 1)
        self.optionVideoAppChooseLocation = QtGui.QPushButton(self.tab_7)
        self.optionVideoAppChooseLocation.setObjectName(_fromUtf8("optionVideoAppChooseLocation"))
        self.gridLayout_4.addWidget(self.optionVideoAppChooseLocation, 1, 2, 1, 1)
        self.label_66 = QtGui.QLabel(self.tab_7)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_4.addWidget(self.label_66, 2, 0, 1, 1)
        self.optionVideoAppParams = QtGui.QLineEdit(self.tab_7)
        self.optionVideoAppParams.setObjectName(_fromUtf8("optionVideoAppParams"))
        self.gridLayout_4.addWidget(self.optionVideoAppParams, 2, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.tab_7)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_4.addWidget(self.label_65, 3, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(498, 36, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.optionsButtonApplyChanges = QtGui.QPushButton(PreferencesDialog)
        self.optionsButtonApplyChanges.setObjectName(_fromUtf8("optionsButtonApplyChanges"))
        self.horizontalLayout_3.addWidget(self.optionsButtonApplyChanges)
        self.optionsButtonCancel = QtGui.QPushButton(PreferencesDialog)
        self.optionsButtonCancel.setObjectName(_fromUtf8("optionsButtonCancel"))
        self.horizontalLayout_3.addWidget(self.optionsButtonCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Settings", None))
        self.label_56.setText(_translate("PreferencesDialog", "Filter search results by these languages:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PreferencesDialog", "Search", None))
        self.groupBox.setTitle(_translate("PreferencesDialog", "Destination folder:", None))
        self.optionDownloadFolderAsk.setText(_translate("PreferencesDialog", "Always ask user", None))
        self.optionDownloadFolderSame.setText(_translate("PreferencesDialog", "Same folder as video file", None))
        self.optionDownloadFolderPredefined.setText(_translate("PreferencesDialog", "Predefined folder:", None))
        self.optionButtonChooseFolder.setText(_translate("PreferencesDialog", "Browse...", None))
        self.groupBox_2.setTitle(_translate("PreferencesDialog", "Filename of the Subtitle:", None))
        self.optionDownloadSameFilename.setText(_translate("PreferencesDialog", "Same name as video file", None))
        self.optionDownloadSameFilenamePlusLang.setText(_translate("PreferencesDialog", "Same name as video file + language code (ex: StarWarsCD1.eng.srt)", None))
        self.optionDownloadSameFilenamePlusLangAndUploader.setText(_translate("PreferencesDialog", "Same name as video file + language code + Uploader name (ex: StarWarsCD1.eng.JohnDoe.srt)", None))
        self.optionDownloadOnlineSubName.setText(_translate("PreferencesDialog", "Same name as the online subtitle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("PreferencesDialog", "Download", None))
        self.label_55.setText(_translate("PreferencesDialog", "Default language of uploaded subtitles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("PreferencesDialog", "Upload", None))
        self.label_52.setText(_translate("PreferencesDialog", "Network Proxy", None))
        self.label_60.setText(_translate("PreferencesDialog", "Host:", None))
        self.label_59.setText(_translate("PreferencesDialog", "Port:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("PreferencesDialog", "Network", None))
        self.label_61.setText(_translate("PreferencesDialog", "Interface Language:", None))
        self.helpTranslateButton.setText(_translate("PreferencesDialog", "Translate This Application...", None))
        self.label_62.setText(_translate("PreferencesDialog", "Context Menu:", None))
        self.optionIntegrationExplorer.setText(_translate("PreferencesDialog", "Enable in your explorer", None))
        self.label_63.setText(_translate("PreferencesDialog", "External application for video playback", None))
        self.label_67.setText(_translate("PreferencesDialog", "Video Player:", None))
        self.optionVideoAppChooseLocation.setText(_translate("PreferencesDialog", "Browse...", None))
        self.label_66.setText(_translate("PreferencesDialog", "Parameters:", None))
        self.label_65.setText(_translate("PreferencesDialog", "{0} = video file path; {1} = subtitle path", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("PreferencesDialog", "Others", None))
        self.optionsButtonApplyChanges.setText(_translate("PreferencesDialog", "Save", None))
        self.optionsButtonCancel.setText(_translate("PreferencesDialog", "Cancel", None))

from . import images_rc

class PreferencesDialog(QtGui.QDialog, Ui_PreferencesDialog):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QDialog.__init__(self, parent, f)

        self.setupUi(self)

