#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Tue Oct 17 21:34:59 2006

import wx

import gettext,locale
import __builtin__





class PanelDirectories(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelDirectories.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.sizer_4_staticbox = wx.StaticBox(self, -1, _("Subtitle download directory:"))
        self.radio_btn_samedir = wx.RadioButton(self, -1, _("Videofiles directory"), style=wx.RB_GROUP)
        self.radio_btn_folder = wx.RadioButton(self, -1, "", style=wx.RB_SINGLE)
        self.text_folder = wx.TextCtrl(self, -1, "")
        self.button_choose = wx.Button(self, -1, _("Choose directory..."))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
	self.Bind(wx.EVT_RADIOBUTTON, self.OnRadioButton2, self.radio_btn_folder)
	self.Bind(wx.EVT_RADIOBUTTON, self.OnRadioButton1, self.radio_btn_samedir)
        self.Bind(wx.EVT_BUTTON, self.OnButtonBrowseDir, self.button_choose)
        # begin wxGlade: PanelDirectories.__set_properties
        self.radio_btn_samedir.SetValue(1)
        self.text_folder.SetMinSize((200, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PanelDirectories.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.radio_btn_samedir, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 6)
        sizer_5.Add(self.radio_btn_folder, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(self.text_folder, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(self.button_choose, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        sizer_3.SetSizeHints(self)
        # end wxGlade
	if self.radio_btn_samedir.GetValue():
	    self.OnRadioButton1(wx.EVT_RADIOBUTTON)
	
    def OnButtonBrowseDir(self,event):
	    dlg = wx.DirDialog(self, _("Please choose directory"),style=wx.DD_DEFAULT_STYLE)
		    
	    if dlg.ShowModal() == wx.ID_OK:
		    self.text_folder.SetValue(dlg.GetPath())
		    dlg.Destroy()
		    
    def OnRadioButton1(self,evt):
	    self.radio_btn_folder.SetValue(False)
	    self.text_folder.Disable()
	    self.button_choose.Disable()
	    
    def OnRadioButton2(self,evt):
	    self.radio_btn_samedir.SetValue(False)
	    self.text_folder.Enable()
	    self.button_choose.Enable()

# end of class PanelDirectories


