#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Tue Aug 29 03:01:53 2006

import wx
import globals
from extra.extendedChoice import ExtendedChoice as EChoice
import  wx.lib.scrolledpanel as scrolled
import wx.lib.hyperlink as hl

import gettext
import __builtin__

class PanelPrefLangs(wx.Panel):

    def __init__(self, *args, **kwds):
	
        # begin wxGlade: PanelPrefLangs.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.sizer_3_staticbox = wx.StaticBox(self, -1, _("Languages:"))
        self.label_app_language = wx.StaticText(self, -1, _("Choose interface language here ..."))
        self.choice_app = wx.Choice(self, -1, choices=[])
        self.static_line_1 = wx.StaticLine(self, -1)
        self.checkbox_search_all_langs = wx.CheckBox(self, -1, _("Search subtitles in ALL the languages"))
        self.scrolled_panel = wx.Panel(self, -1)
        self.static_line_2 = wx.StaticLine(self, -1)
        self.checkbox_autodetect_upload = wx.CheckBox(self, -1, _("Autodetect Language in Upload"))
        self.label_choice_upload = wx.StaticText(self, -1, _("Default Upload Language:"))
        self.choice_upload = wx.Choice(self, -1, choices=[])

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        
        # begin wxGlade: PanelPrefLangs.__set_properties
        self.checkbox_search_all_langs.SetValue(1)
        self.scrolled_panel.SetMinSize((300, 100))
        self.checkbox_autodetect_upload.SetValue(1)
        # end wxGlade
	
	self.InitComponents()

    def __do_layout(self):

        # begin wxGlade: PanelPrefLangs.__do_layout
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.label_app_language, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 20)
        sizer_1.Add(self.choice_app, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_1, 0, wx.TOP|wx.EXPAND, 4)
        sizer_3.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_3.Add(self.checkbox_search_all_langs, 0, wx.TOP|wx.ADJUST_MINSIZE, 11)
        sizer_3.Add(self.scrolled_panel, 0, 0, 0)
        sizer_3.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_3.Add(self.checkbox_autodetect_upload, 0, wx.TOP|wx.ADJUST_MINSIZE, 11)
        sizer_2.Add(self.label_choice_upload, 0, wx.LEFT|wx.ADJUST_MINSIZE, 20)
        sizer_2.Add(self.choice_upload, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_2, 0, wx.TOP|wx.EXPAND, 8)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        sizer_3.SetSizeHints(self)
        # end wxGlade

    
    def InitComponents(self):
	#self.choice_app.Destroy()
	#self.choice_upload.Destroy()
	#self.choice_app = EChoice.ExtendedChoice(self, -1,size=(150,20), choices=self.choices1,
                                                  #icons=self.Images,
                                                  #extrastyle=EChoice.EC_CHOICE,
                                                  #name="SimpleExtendedChoice")
	
	#self.choice_upload = EChoice.ExtendedChoice(self, -1,size=(150,20), choices=self.choices1,
                                                  #icons=self.Images,
                                                  #extrastyle=EChoice.EC_CHOICE,
                                                  #name="SimpleExtendedChoice")
	languages = []
	for lang in globals.new_translations_dates.keys():
	    languages_xxx = globals.sublanguages["languages_xx2xxx"][lang]
	    languages.append(globals.sublanguages["languages_id_xxx"][languages_xxx][1])
	    
	languages.sort()
	for lang in languages:
		self.choice_app.Append(lang)
	    
	languages = []
	for xx,xxx in globals.sublanguages["languages_xx2xxx"].items():
		languages.append(globals.sublanguages["languages_id_xxx"][xxx][1])
	languages.sort()
	for lang in languages:
		self.choice_upload.Append(lang)
		
	
	self.scrolled_panel.Destroy()
	self.scrolled_panel = scrolled.ScrolledPanel(self, -1, size= (140, 300),
                                 style = wx.TAB_TRAVERSAL|wx.SUNKEN_BORDER, name="panel1" )
	
	self.gridsizer = wx.FlexGridSizer(cols=4, vgap=4, hgap=0)
	
	self.langs_checkboxes = {}
	
	for xx,xxx in globals.sublanguages["languages_xx2xxx"].items():
	    name = globals.sublanguages["languages_id_xxx"][xxx][1]
	    #bitmap = wx.StaticBitmap(self.scrolled_panel, -1, globals.flag_bitmaps[xx])
	    sizer = wx.BoxSizer(wx.HORIZONTAL)
	    checkbox_lang = wx.CheckBox(self.scrolled_panel, -1, name)
	    self.langs_checkboxes[xxx] = checkbox_lang
	    #sizer.Add(bitmap, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 2)
	    sizer.Add(checkbox_lang, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 20)
	    self.gridsizer.Add(sizer, 0, wx.EXPAND|wx.ALIGN_LEFT)
	    
	self.scrolled_panel.SetSizer( self.gridsizer )
        self.scrolled_panel.SetAutoLayout(1)
        self.scrolled_panel.SetupScrolling()
	self.scrolled_panel.SetMinSize((500, 150))
	self.scrolled_panel.Disable()
	
	self.choice_upload.SetStringSelection(globals.sublanguages["languages_id_xxx"]["eng"][1])
	self.choice_app.SetStringSelection(globals.sublanguages["languages_id_xxx"]["eng"][1])
	#self.choice_upload.SortChoices()
	#self.choice_app.SortChoices()
	
	self.Bind(wx.EVT_CHECKBOX, self.OnCheckAllSubtitlesLangs, self.checkbox_search_all_langs)
	self.Bind(wx.EVT_CHECKBOX, self.OnCheckAutodetectUploadLang, self.checkbox_autodetect_upload)

	
    def OnCheckAutodetectUploadLang(self,evt):
	if self.checkbox_autodetect_upload.IsChecked():
	    self.label_choice_upload.Disable()
	    self.choice_upload.Disable()
	else:
	    self.label_choice_upload.Enable()
	    self.choice_upload.Enable()
    def OnCheckAllSubtitlesLangs(self,evt):
	if self.checkbox_search_all_langs.IsChecked():
	    self.scrolled_panel.Disable()
	else:
	    self.scrolled_panel.Enable()
	    

	
	
# end of class PanelPrefLangs


