# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 577)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/subdownloader.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(88, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(88, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.buttonSearchSelectVideos = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSearchSelectVideos.sizePolicy().hasHeightForWidth())
        self.buttonSearchSelectVideos.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/open_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSearchSelectVideos.setIcon(icon1)
        self.buttonSearchSelectVideos.setIconSize(QtCore.QSize(16, 16))
        self.buttonSearchSelectVideos.setObjectName("buttonSearchSelectVideos")
        self.horizontalLayout_6.addWidget(self.buttonSearchSelectVideos)
        self.buttonSearchSelectFolder = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSearchSelectFolder.sizePolicy().hasHeightForWidth())
        self.buttonSearchSelectFolder.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/open_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSearchSelectFolder.setIcon(icon2)
        self.buttonSearchSelectFolder.setIconSize(QtCore.QSize(16, 16))
        self.buttonSearchSelectFolder.setObjectName("buttonSearchSelectFolder")
        self.horizontalLayout_6.addWidget(self.buttonSearchSelectFolder)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.folderView = QtWidgets.QTreeView(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderView.sizePolicy().hasHeightForWidth())
        self.folderView.setSizePolicy(sizePolicy)
        self.folderView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.folderView.setObjectName("folderView")
        self.verticalLayout_3.addWidget(self.folderView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonRefresh = QtWidgets.QPushButton(self.frame_2)
        self.buttonRefresh.setEnabled(True)
        self.buttonRefresh.setMaximumSize(QtCore.QSize(5000, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonRefresh.setFont(font)
        self.buttonRefresh.setCheckable(False)
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.horizontalLayout_4.addWidget(self.buttonRefresh)
        self.buttonFind = QtWidgets.QPushButton(self.frame_2)
        self.buttonFind.setEnabled(False)
        self.buttonFind.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonFind.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFind.setIcon(icon3)
        self.buttonFind.setIconSize(QtCore.QSize(16, 16))
        self.buttonFind.setObjectName("buttonFind")
        self.horizontalLayout_4.addWidget(self.buttonFind)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox_videosFound = QtWidgets.QFrame(self.splitter)
        self.groupBox_videosFound.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupBox_videosFound.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupBox_videosFound.setObjectName("groupBox_videosFound")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_videosFound)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layoutTopVideos = QtWidgets.QHBoxLayout()
        self.layoutTopVideos.setObjectName("layoutTopVideos")
        self.label_videosFound = QtWidgets.QLabel(self.groupBox_videosFound)
        self.label_videosFound.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_videosFound.setObjectName("label_videosFound")
        self.layoutTopVideos.addWidget(self.label_videosFound)
        spacerItem2 = QtWidgets.QSpacerItem(88, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutTopVideos.addItem(spacerItem2)
        self.label_filterBy = QtWidgets.QLabel(self.groupBox_videosFound)
        self.label_filterBy.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_filterBy.setFont(font)
        self.label_filterBy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filterBy.setObjectName("label_filterBy")
        self.layoutTopVideos.addWidget(self.label_filterBy)
        self.filterLanguageForVideo = QtWidgets.QComboBox(self.groupBox_videosFound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLanguageForVideo.sizePolicy().hasHeightForWidth())
        self.filterLanguageForVideo.setSizePolicy(sizePolicy)
        self.filterLanguageForVideo.setMinimumSize(QtCore.QSize(100, 0))
        self.filterLanguageForVideo.setObjectName("filterLanguageForVideo")
        self.layoutTopVideos.addWidget(self.filterLanguageForVideo)
        self.verticalLayout_8.addLayout(self.layoutTopVideos)
        self.videoView = QtWidgets.QTreeView(self.groupBox_videosFound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoView.sizePolicy().hasHeightForWidth())
        self.videoView.setSizePolicy(sizePolicy)
        self.videoView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.videoView.setAlternatingRowColors(True)
        self.videoView.setObjectName("videoView")
        self.verticalLayout_8.addWidget(self.videoView)
        self.introductionHelp = QtWidgets.QTextBrowser(self.groupBox_videosFound)
        self.introductionHelp.setObjectName("introductionHelp")
        self.verticalLayout_8.addWidget(self.introductionHelp)
        self.layoutBottomVideos = QtWidgets.QHBoxLayout()
        self.layoutBottomVideos.setObjectName("layoutBottomVideos")
        self.buttonIMDB = QtWidgets.QPushButton(self.groupBox_videosFound)
        self.buttonIMDB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonIMDB.sizePolicy().hasHeightForWidth())
        self.buttonIMDB.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonIMDB.setIcon(icon4)
        self.buttonIMDB.setIconSize(QtCore.QSize(32, 16))
        self.buttonIMDB.setObjectName("buttonIMDB")
        self.layoutBottomVideos.addWidget(self.buttonIMDB)
        spacerItem3 = QtWidgets.QSpacerItem(13, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutBottomVideos.addItem(spacerItem3)
        self.buttonPlay = QtWidgets.QPushButton(self.groupBox_videosFound)
        self.buttonPlay.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlay.sizePolicy().hasHeightForWidth())
        self.buttonPlay.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPlay.setIcon(icon5)
        self.buttonPlay.setObjectName("buttonPlay")
        self.layoutBottomVideos.addWidget(self.buttonPlay)
        self.buttonDownload = QtWidgets.QPushButton(self.groupBox_videosFound)
        self.buttonDownload.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDownload.sizePolicy().hasHeightForWidth())
        self.buttonDownload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonDownload.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDownload.setIcon(icon6)
        self.buttonDownload.setObjectName("buttonDownload")
        self.layoutBottomVideos.addWidget(self.buttonDownload)
        self.verticalLayout_8.addLayout(self.layoutBottomVideos)
        self.verticalLayout_6.addWidget(self.splitter)
        self.verticalLayout_4.addWidget(self.frame)
        self.tabs.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.movieNameText = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieNameText.sizePolicy().hasHeightForWidth())
        self.movieNameText.setSizePolicy(sizePolicy)
        self.movieNameText.setText("")
        self.movieNameText.setObjectName("movieNameText")
        self.horizontalLayout.addWidget(self.movieNameText)
        self.buttonSearchByName = QtWidgets.QPushButton(self.tab_3)
        self.buttonSearchByName.setIcon(icon3)
        self.buttonSearchByName.setFlat(False)
        self.buttonSearchByName.setObjectName("buttonSearchByName")
        self.horizontalLayout.addWidget(self.buttonSearchByName)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(26, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.searchSitesCombo = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchSitesCombo.sizePolicy().hasHeightForWidth())
        self.searchSitesCombo.setSizePolicy(sizePolicy)
        self.searchSitesCombo.setObjectName("searchSitesCombo")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/sites/opensubtitles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchSitesCombo.addItem(icon7, "")
        self.horizontalLayout_2.addWidget(self.searchSitesCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem5 = QtWidgets.QSpacerItem(118, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.filterLanguageForTitle = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLanguageForTitle.sizePolicy().hasHeightForWidth())
        self.filterLanguageForTitle.setSizePolicy(sizePolicy)
        self.filterLanguageForTitle.setMinimumSize(QtCore.QSize(100, 0))
        self.filterLanguageForTitle.setObjectName("filterLanguageForTitle")
        self.horizontalLayout_8.addWidget(self.filterLanguageForTitle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.moviesView = QtWidgets.QTreeView(self.tab_3)
        self.moviesView.setAlternatingRowColors(True)
        self.moviesView.setObjectName("moviesView")
        self.verticalLayout_2.addWidget(self.moviesView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonIMDBByTitle = QtWidgets.QPushButton(self.tab_3)
        self.buttonIMDBByTitle.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonIMDBByTitle.sizePolicy().hasHeightForWidth())
        self.buttonIMDBByTitle.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/imdb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonIMDBByTitle.setIcon(icon8)
        self.buttonIMDBByTitle.setIconSize(QtCore.QSize(32, 16))
        self.buttonIMDBByTitle.setObjectName("buttonIMDBByTitle")
        self.horizontalLayout_3.addWidget(self.buttonIMDBByTitle)
        spacerItem6 = QtWidgets.QSpacerItem(118, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.buttonDownloadByTitle = QtWidgets.QPushButton(self.tab_3)
        self.buttonDownloadByTitle.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDownloadByTitle.sizePolicy().hasHeightForWidth())
        self.buttonDownloadByTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonDownloadByTitle.setFont(font)
        self.buttonDownloadByTitle.setIcon(icon6)
        self.buttonDownloadByTitle.setObjectName("buttonDownloadByTitle")
        self.horizontalLayout_3.addWidget(self.buttonDownloadByTitle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.tab_4)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.vboxlayout2 = QtWidgets.QVBoxLayout()
        self.vboxlayout2.setSpacing(1)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonUploadBrowseFolder = QtWidgets.QToolButton(self.groupBox_2)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/openfolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUploadBrowseFolder.setIcon(icon9)
        self.buttonUploadBrowseFolder.setIconSize(QtCore.QSize(24, 24))
        self.buttonUploadBrowseFolder.setObjectName("buttonUploadBrowseFolder")
        self.horizontalLayout_5.addWidget(self.buttonUploadBrowseFolder)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.buttonUploadPlusRow = QtWidgets.QToolButton(self.groupBox_2)
        self.buttonUploadPlusRow.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUploadPlusRow.setIcon(icon10)
        self.buttonUploadPlusRow.setIconSize(QtCore.QSize(24, 24))
        self.buttonUploadPlusRow.setObjectName("buttonUploadPlusRow")
        self.horizontalLayout_5.addWidget(self.buttonUploadPlusRow)
        self.buttonUploadMinusRow = QtWidgets.QToolButton(self.groupBox_2)
        self.buttonUploadMinusRow.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUploadMinusRow.setIcon(icon11)
        self.buttonUploadMinusRow.setIconSize(QtCore.QSize(24, 24))
        self.buttonUploadMinusRow.setObjectName("buttonUploadMinusRow")
        self.horizontalLayout_5.addWidget(self.buttonUploadMinusRow)
        self.buttonUploadDeleteAllRow = QtWidgets.QToolButton(self.groupBox_2)
        self.buttonUploadDeleteAllRow.setEnabled(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/delete_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUploadDeleteAllRow.setIcon(icon12)
        self.buttonUploadDeleteAllRow.setIconSize(QtCore.QSize(24, 24))
        self.buttonUploadDeleteAllRow.setObjectName("buttonUploadDeleteAllRow")
        self.horizontalLayout_5.addWidget(self.buttonUploadDeleteAllRow)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.buttonUploadUpRow = QtWidgets.QToolButton(self.groupBox_2)
        self.buttonUploadUpRow.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUploadUpRow.setIcon(icon13)
        self.buttonUploadUpRow.setIconSize(QtCore.QSize(24, 24))
        self.buttonUploadUpRow.setObjectName("buttonUploadUpRow")
        self.horizontalLayout_5.addWidget(self.buttonUploadUpRow)
        self.buttonUploadDownRow = QtWidgets.QToolButton(self.groupBox_2)
        self.buttonUploadDownRow.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUploadDownRow.setIcon(icon14)
        self.buttonUploadDownRow.setIconSize(QtCore.QSize(24, 24))
        self.buttonUploadDownRow.setObjectName("buttonUploadDownRow")
        self.horizontalLayout_5.addWidget(self.buttonUploadDownRow)
        spacerItem7 = QtWidgets.QSpacerItem(401, 33, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.uploadView = UploadListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadView.sizePolicy().hasHeightForWidth())
        self.uploadView.setSizePolicy(sizePolicy)
        self.uploadView.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadView.setBaseSize(QtCore.QSize(0, 0))
        self.uploadView.setAcceptDrops(True)
        self.uploadView.setDragEnabled(True)
        self.uploadView.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.uploadView.setAlternatingRowColors(True)
        self.uploadView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.uploadView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uploadView.setGridStyle(QtCore.Qt.DotLine)
        self.uploadView.setObjectName("uploadView")
        self.verticalLayout.addWidget(self.uploadView)
        self.vboxlayout2.addWidget(self.groupBox_2)
        self.uploadDetailsGroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.uploadDetailsGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.uploadDetailsGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uploadDetailsGroupBox.setObjectName("uploadDetailsGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.uploadDetailsGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.uploadIMDB = QtWidgets.QComboBox(self.uploadDetailsGroupBox)
        self.uploadIMDB.setObjectName("uploadIMDB")
        self.uploadIMDB.addItem("")
        self.gridLayout.addWidget(self.uploadIMDB, 1, 2, 1, 1)
        self.buttonUploadFindIMDB = QtWidgets.QPushButton(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUploadFindIMDB.sizePolicy().hasHeightForWidth())
        self.buttonUploadFindIMDB.setSizePolicy(sizePolicy)
        self.buttonUploadFindIMDB.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonUploadFindIMDB.setMaximumSize(QtCore.QSize(120, 16777215))
        self.buttonUploadFindIMDB.setIcon(icon3)
        self.buttonUploadFindIMDB.setObjectName("buttonUploadFindIMDB")
        self.gridLayout.addWidget(self.buttonUploadFindIMDB, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_autodetect_imdb = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        self.label_autodetect_imdb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_autodetect_imdb.sizePolicy().hasHeightForWidth())
        self.label_autodetect_imdb.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_autodetect_imdb.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_autodetect_imdb.setFont(font)
        self.label_autodetect_imdb.setLineWidth(0)
        self.label_autodetect_imdb.setTextFormat(QtCore.Qt.PlainText)
        self.label_autodetect_imdb.setScaledContents(False)
        self.label_autodetect_imdb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_autodetect_imdb.setObjectName("label_autodetect_imdb")
        self.gridLayout.addWidget(self.label_autodetect_imdb, 0, 2, 1, 1)
        self.label_autodetect_lang = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_autodetect_lang.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_autodetect_lang.setFont(font)
        self.label_autodetect_lang.setTextFormat(QtCore.Qt.PlainText)
        self.label_autodetect_lang.setObjectName("label_autodetect_lang")
        self.gridLayout.addWidget(self.label_autodetect_lang, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.uploadReleaseText = QtWidgets.QLineEdit(self.uploadDetailsGroupBox)
        self.uploadReleaseText.setObjectName("uploadReleaseText")
        self.gridLayout.addWidget(self.uploadReleaseText, 4, 2, 1, 1)
        self.uploadComments = QtWidgets.QTextEdit(self.uploadDetailsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadComments.sizePolicy().hasHeightForWidth())
        self.uploadComments.setSizePolicy(sizePolicy)
        self.uploadComments.setMaximumSize(QtCore.QSize(16777215, 50))
        self.uploadComments.setObjectName("uploadComments")
        self.gridLayout.addWidget(self.uploadComments, 5, 2, 1, 1)
        self.buttonUpload = QtWidgets.QPushButton(self.uploadDetailsGroupBox)
        self.buttonUpload.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonUpload.setFont(font)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUpload.setIcon(icon15)
        self.buttonUpload.setIconSize(QtCore.QSize(24, 24))
        self.buttonUpload.setObjectName("buttonUpload")
        self.gridLayout.addWidget(self.buttonUpload, 5, 3, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.uploadLanguages = QtWidgets.QComboBox(self.uploadDetailsGroupBox)
        self.uploadLanguages.setObjectName("uploadLanguages")
        self.horizontalLayout_12.addWidget(self.uploadLanguages)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_12, 2, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.vboxlayout2.addWidget(self.uploadDetailsGroupBox)
        self.vboxlayout1.addLayout(self.vboxlayout2)
        self.tabs.addTab(self.tab_4, "")
        self.vboxlayout.addWidget(self.tabs)
        self.verticalLayout_5.addLayout(self.vboxlayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 714, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Preferences = QtWidgets.QMenu(self.menuBar)
        self.menu_Preferences.setObjectName("menu_Preferences")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon16)
        self.action_Quit.setObjectName("action_Quit")
        self.action_HelpHomepage = QtWidgets.QAction(MainWindow)
        self.action_HelpHomepage.setObjectName("action_HelpHomepage")
        self.action_HelpAbout = QtWidgets.QAction(MainWindow)
        self.action_HelpAbout.setObjectName("action_HelpAbout")
        self.action_HelpBug = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_HelpBug.setIcon(icon17)
        self.action_HelpBug.setObjectName("action_HelpBug")
        self.action_ShowPreferences = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ShowPreferences.setIcon(icon18)
        self.action_ShowPreferences.setObjectName("action_ShowPreferences")
        self.action_Login = QtWidgets.QAction(MainWindow)
        self.action_Login.setObjectName("action_Login")
        self.action_LogMessages = QtWidgets.QAction(MainWindow)
        self.action_LogMessages.setEnabled(False)
        self.action_LogMessages.setObjectName("action_LogMessages")
        self.action_ShowHideTreeFolder = QtWidgets.QAction(MainWindow)
        self.action_ShowHideTreeFolder.setCheckable(True)
        self.action_ShowHideTreeFolder.setChecked(True)
        self.action_ShowHideTreeFolder.setEnabled(False)
        self.action_ShowHideTreeFolder.setObjectName("action_ShowHideTreeFolder")
        self.action_LogOut = QtWidgets.QAction(MainWindow)
        self.action_LogOut.setEnabled(False)
        self.action_LogOut.setObjectName("action_LogOut")
        self.action_HelpTranslate = QtWidgets.QAction(MainWindow)
        self.action_HelpTranslate.setObjectName("action_HelpTranslate")
        self.menuMain.addAction(self.action_Login)
        self.menuMain.addAction(self.action_LogOut)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.action_Quit)
        self.menu_Help.addAction(self.action_HelpHomepage)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_HelpBug)
        self.menu_Help.addAction(self.action_HelpTranslate)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_HelpAbout)
        self.menu_Preferences.addAction(self.action_ShowPreferences)
        self.menuView.addAction(self.action_LogMessages)
        self.menuView.addAction(self.action_ShowHideTreeFolder)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menu_Preferences.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_("SubDownloader"))
        self.label_11.setText(_("Select the video/folder that needs subtitles:"))
        self.buttonSearchSelectVideos.setToolTip(_("Select videos that need subtitles"))
        self.buttonSearchSelectVideos.setText(_("Select videos..."))
        self.buttonSearchSelectFolder.setToolTip(_("Click here to Search the subtitles of the movies in that folder"))
        self.buttonSearchSelectFolder.setText(_("Select folder..."))
        self.buttonRefresh.setText(_("Refresh list"))
        self.buttonFind.setToolTip(_("Click here to Search the subtitles of the movies in that folder"))
        self.buttonFind.setText(_("Search subtitles"))
        self.label_videosFound.setText(_("Videos/Subtitles found:"))
        self.label_filterBy.setText(_("Filter by:"))
        self.introductionHelp.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:600;\"><br /></p></body></html>"))
        self.buttonIMDB.setText(_("Movie Info"))
        self.buttonPlay.setText(_("Play"))
        self.buttonDownload.setText(_("Download"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _("Search from Video file(s)"))
        self.buttonSearchByName.setText(_("Search"))
        self.label_3.setText(_("Site:"))
        self.searchSitesCombo.setItemText(0, _("OpenSubtitles.org"))
        self.label_12.setText(_("Subtitles found:"))
        self.label_10.setText(_("Filter by :"))
        self.buttonIMDBByTitle.setText(_("Movie Info"))
        self.buttonDownloadByTitle.setText(_("Download"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _("Search by Movie Name"))
        self.groupBox_2.setTitle(_("Select the videos and subtitles  (only subtitles will be uploaded):"))
        self.buttonUploadBrowseFolder.setText(_("..."))
        self.buttonUploadPlusRow.setText(_("..."))
        self.buttonUploadMinusRow.setText(_("..."))
        self.buttonUploadDeleteAllRow.setToolTip(_("Empty the list"))
        self.buttonUploadDeleteAllRow.setText(_("..."))
        self.buttonUploadUpRow.setText(_("..."))
        self.buttonUploadDownRow.setText(_("..."))
        self.uploadDetailsGroupBox.setTitle(_("Details:"))
        self.label_4.setText(_translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">*</span></p></body></html>"))
        self.label.setText(_("Movie Title:"))
        self.uploadIMDB.setItemText(0, _("Click on the Find button to identify the movie"))
        self.buttonUploadFindIMDB.setText(_("Find"))
        self.label_8.setText(_translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">*</span></p></body></html>"))
        self.label_autodetect_imdb.setText(_("..."))
        self.label_autodetect_lang.setText(_("..."))
        self.label_6.setText(_("Release name:"))
        self.label_7.setText(_("Comments:"))
        self.label_5.setText(_("Subtitle Language:"))
        self.buttonUpload.setText(_("Upload"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _("Upload subtitles"))
        self.menuMain.setTitle(_("&Main"))
        self.menu_Help.setTitle(_("&Help"))
        self.menu_Preferences.setTitle(_("&Settings"))
        self.menuView.setTitle(_("&View"))
        self.action_Quit.setText(_("Quit"))
        self.action_HelpHomepage.setText(_("Visit HomePage"))
        self.action_HelpAbout.setText(_("About"))
        self.action_HelpBug.setText(_("Report A Problem"))
        self.action_ShowPreferences.setText(_("&Configure Subdownloader"))
        self.action_Login.setText(_("LogIn"))
        self.action_LogMessages.setText(_("Log Messages"))
        self.action_ShowHideTreeFolder.setText(_("Show/Hide Tree Folder"))
        self.action_LogOut.setText(_("LogOut"))
        self.action_HelpTranslate.setText(_("Translate This Application..."))

from .uploadlistview import UploadListView
from . import images_rc
